export enum Routes {
    NAVIGATION_HOME_ROUTE= 'События',
    CALENDAR_ROUTE= 'Календарь',
    COMMUNITY_LIST_ROUTE= 'Коммьюнити',
    PROFILE_ROUTE= 'Профиль',
    // NAVIGATION_HOME_ROUTE= 'NavigationHome',
    // CALENDAR_ROUTE= 'Calendar',
    // COMMUNITY_ROUTE= 'CommunityList',
    // PROFILE_ROUTE= 'Profile',

    EVENT_SEARCH_ROUTE= 'EventSearch',
    LIST_CREATED_EVENTS_ROUTE= 'ListCreatedEvents',
    VERIFICATION_ROUTE= 'Verification',
    CREATING_EVENT_ROUTE= 'CreatingEvent',
    COMMUNITY_ROUTE= 'Community',
    OTHER_PROFILE_ROUTE= 'OtherProfile',
    EVENT_ROUTE= 'Event',
    ADVERTISING_ROUTE= 'Advertising',
    REGISTRATION_ON_EVENT_ROUTE= 'RegistrationOnEvent',
    FAVORITE_ROUTE= 'Favorite',
    CREATE_COMMUNITY_ROUTE = 'CreateCommunity',
    NAVIGATION_ROUTE= 'Navigation',
    REGISTRATION_ROUTE= 'Registration',
    AUTH_ROUTE= 'Auth',
    SELECT_FAVORITE_ROUTE= 'SelectFavorite',
    MAIN_ROUTE= 'Main',
}